name: HACS Validate

on:
  pull_request:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
